title: Lakaxita
tagline: Irungo Lakaxita Gaztetxea
author:
    name: Lakaxita
    email: lakaxita@gmail.com
    github: lakaxita

production_url: http://lakaxita.org/
admin_url: http://prose.io/#lakaxita/lakaxita.github.io
permalink: /:categories/:year/:month/:day/:title

gems:
    - jekyll-compass
exclude: [".rvmrc", ".rbenv-version", "Rakefile", "vendor"]
pygments: true
markdown: redcarpet
redcarpet:
    extensions: ["tables", "autolink", "fenced_code_blocks", "superscript",
                "quote", "footnotes"]

JB:
    BASE_PATH: false
    ASSET_PATH: /static/
    atom_path: /atom.xml
    rss_path: /rss.xml
    comments:
        provider: false
    analytics:
        provider: false
    sharing:
        provider: false

prose:
    siteurl: "http://lakaxita.org"
    media: "media"
    ignore:
        - .compass
        - _data
        - 404.html
        - static
        - CNAME
        - _config.yml
        - Gemfile
        - Gemfile.lock
        - _includes
        - json
        - _layouts
        - _site
        - sitemap.txt
        - .gitignore
        - .travis.yml
    metadata:
        "":
            -
                name: "title"
                field:
                    label: "Title"
                    element: "text"
        _posts:
            -
                name: "author"
                field:
                    label: "Author"
                    element: "text"
                    value: "Lakaxita"
