# General
title: Lakaxita
tagline: Irungo Lakaxita Gaztetxea
description: >
    Lakaxita pertsona eta kolektibo ezberdinek autogestionatzen duten gune
    okupatua da. Gure inguruko gabezia sozial eta kulturaletaz arduratzen gara
    eta haiei aurre egitea da gure erronka nagusia.
author:
    name: Lakaxita
    email: lakaxita@gmail.com
    github: lakaxita
timezone: "Europe/Paris"

permalink: pretty
baseurl: /

exclude: [".rvmrc", ".rbenv-version", "Rakefile", "vendor"]
excerpt_separator: "<!--break-->"
markdown: kramdown
